### ISSUE TITLE
Get I18n via translatwiki rolling

### ISSUE THREAD

**Issue by kghbln** [ProfessionalWiki/WikibaseRDF#1]
- [x] 1) Add repo to user group with push rights
- [x] 2) Review "en.json" and extend "qqq.json"
- [x] 3) Create pull to add extension to twn --> https://gerrit.wikimedia.org/r/c/translatewiki/+/818994

**Comment by JeroenDeDauw** [comment]
@kghbln this can already be done

**Comment by kghbln** [comment]
All of this: done!

**Comment by JeroenDeDauw** [comment]
> All of this: done!

You really took a liking to that Bernie meme :D
