### ISSUE TITLE
Link URLs on entity pages

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/WikibaseRDF#103]
From @paulduchesne:

> it would be really useful to be able to click through the URL links (which we are now expecting to only be validated URLs)

AC:

* URLs are linked.
* Visually similar to links in WB statements
* Should have nofollow by default. It's nice (but not required) if the usual MW config about nofollow is respected, especially if that is also the case for URLs in statements.

---

We definitely need nofollow on those URL if we link them. Good to check what wikibase does for statements with link values.

**Comment by malberts** [comment]
Example from Wikibase:
```html
<a rel="nofollow" class="external free" href="https://www.wikidata.org/wiki/Q455552">https://www.wikidata.org/wiki/Q455552</a>
```

**Comment by JeroenDeDauw** [comment]
Let's just do the same then. Presumably, Wikibase is using the standard MW link building, which adds nofollow and such, based on various config.
