### ISSUE TITLE
UX: add plus sign next to "add mapping"

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/WikibaseRDF#108]
To make it consistent with the statement UI

![image](https://user-images.githubusercontent.com/146040/193848442-6bb080f1-d32e-477f-822e-57761ec26c8a.png)

**Comment by malberts** [comment]
Under what conditions did this happen? Or is it always missing?

It is there on localhost:
![Screenshot_20221004_164906](https://user-images.githubusercontent.com/1428594/193851536-220facea-1dbb-4650-abf0-3b45e5db6c91.png)

**Comment by malberts** [comment]
It's working now.

![Screenshot_20221004_190525](https://user-images.githubusercontent.com/1428594/193882211-392b813b-e48d-4dae-ba2b-dc059a3cc119.png)
