### ISSUE TITLE
Make the editing UI layout nice

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/WikibaseRDF#28]
AC:

* Does not look out of place
* Proper and consistent spacing and other CSS stuffs

(Up to the judgment of the implementer :))

**Comment by malberts** [comment]
I'm going to use this as the task to implement the actual JS to make the UI functional. Or do we want to track that separately and use this only for styling?

**Comment by JeroenDeDauw** [comment]
Up to you

**Comment by JeroenDeDauw** [comment]
I created a dedicated task since getting edit to work is much higher prior than styling the UI
