### ISSUE TITLE
Return success indicator in SaveMappingsApi

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/WikibaseRDF#33]
Replace 

```php
return [
			'mappings' => $mappings->asArray(),
		];
```

with some simple success indicator. Preferably following a standard if there is one for such MW REST API modules

**Comment by JeroenDeDauw** [comment]
@malberts why did you return the list of mappings? That does not seem very useful if the client just sent that list. Or am I missing something?

**Comment by malberts** [comment]
> @malberts why did you return the list of mappings? That does not seem very useful if the client just sent that list. Or am I missing something?

That was just to return something. We don't need that, but we do need something as per this issue. I imagine that our save logic would be an all-or-nothing event, so we shouldn't end up in a situation where only some of the mappings are saved (in which case it might be useful to return what was saved successfully).

**Comment by malberts** [comment]
As per https://github.com/ProfessionalWiki/WikibaseRDF/pull/46#discussion_r930102300 an HTTP status code should be sufficient. If anything else is needed we can add it later.
