### ISSUE TITLE
Validater that the object/URL is a valid URL

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/WikibaseRDF#37]
Blocker: clarify prefix behavior. (https://github.com/ProfessionalWiki/WikibaseRDF/discussions/20#discussioncomment-3203399)

~~AC:~~

* [ ] Check that the string value is a valid URL on the backend
* [ ] Provide error output in the write API is it is not

No web request should be made to the URL to see if it is live

**Comment by malberts** [comment]
Is this closed because we're not going to add validation, or do we need more info from the linked discussion before continuing?

**Comment by JeroenDeDauw** [comment]
There is currently no requirement from the client to restrict the object values.
