### ISSUE TITLE
Add SaveMappingsAPI authentication

### ISSUE THREAD

**Issue by malberts** [ProfessionalWiki/WikibaseRDF#45]
From https://github.com/ProfessionalWiki/WikibaseRDF/discussions/34#discussioncomment-3228551

**Comment by JeroenDeDauw** [comment]
I was expecting read and write permissions to already be checked via the code called in `SlotEntityContentRepository`. After all that code takes the current User/Authority. Apparently not. I can write to the content slot via our write API using the curl command from the README, even though the wiki only allows write from registered users. 

Maybe there is a way to tell MediaWiki what the read and write permissions for a slot are? 

There might also be a way to tag required permissions in the API. Normally permission check is done in the UC, but if we can make things work nicely for little effort via a standard MW approach, then that is also a viable approach.

**Comment by JeroenDeDauw** [comment]
From `ApiEditSlot.php` in wsslots:

```php
// Check if we are allowed to edit or create this page
		$this->checkTitleUserPermissions(
			$title_object,
			$title_object->exists() ? 'edit' : [ 'edit', 'create' ],
  			[ 'autoblock' => true ]
  		);
```

**Comment by malberts** [comment]
Some notes:

When calling the save API with MW's REST client (as in #60), it is throwing an anonymous error when the user is nog logged in:
![Screenshot_20220802_220716](https://user-images.githubusercontent.com/1428594/182463789-4c4074e6-4f83-42aa-9eb2-c1d0200e24a6.png)
However, that is unrelated to any permission logic we added explicitly.

`checkTitleUserPermissions()` comes from `ApiBase` which is not related to the `SimpleHandler` base class we use. Perhaps we should be using the former when the API is directly involved with touching pages whereas the REST base class might be more generic and unaware of the page. I will investigage.
