### ISSUE TITLE
Add web API to save mappings for an entity

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/WikibaseRDF#5]
This is needed by the UI we will add on entity pages, to save changes.

AC:
* new web API, preferably using the "new" REST stuff
* takes an EntityID and a serialization of all the mappings for that entity

Not included (only in a follow up): actually persisting the data: https://github.com/ProfessionalWiki/WikibaseRDF/issues/7

**Comment by JeroenDeDauw** [comment]
Actually, if MediaWiki allows writing to a slot directly, via an existing API, then perhaps we can use that. We would likely need to then detect that via some hook, so we can run additional code, such as storage in an additional table, if that turns out to be needed.

**Comment by hexmode** [comment]
> Actually, if MediaWiki allows writing to a slot directly, via an existing API, then perhaps we can use that. We would likely need to then detect that via some hook, so we can run additional code, such as storage in a new db table, if that turns out to be needed.

Looks like [this is not possible](https://www.mediawiki.org/wiki/Multi-Content_Revisions) (at least as of 2020):
> Note that per 2020, no API or UI will automatically become available to interact with content in the slot. Extension authors will have to implement their own API modules and UI components based on the storage layer functionality described above.
