### ISSUE TITLE
Improve error handling in the UI

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/WikibaseRDF#66]
> Improve API error UX. Currently just dumping the JSON response - I need to figure out if the current localized message response is the best way.

Follow up to https://github.com/ProfessionalWiki/WikibaseRDF/pull/60

**Comment by malberts** [comment]
We can follow up on https://github.com/ProfessionalWiki/WikibaseRDF/pull/76#issuecomment-1209576393 separately if necessary.
