### ISSUE TITLE
About "MediaWiki:Wikibase-rdf-config-invalid"

### ISSUE THREAD

**Issue by kghbln** [ProfessionalWiki/WikibaseRDF#85]
I guess that `$1` holds the name of the invalid pedicate. Not absolutely sure though.

**Comment by malberts** [comment]
That contains a _list_ of invalid predicates. The string value is generated in the code by adding quotes and commas:
![Screenshot_20220819_102920](https://user-images.githubusercontent.com/1428594/185578063-ed9322d5-9e36-442e-be14-0d996a6569e7.png)

**Comment by kghbln** [comment]
Thanks for clarifying. I updated the message documentation. Changes will roll in tomorrow with translation updates.

**Comment by kghbln** [comment]
Hmm, I believe "Invalid predicates:" should support plural in this case. The question is if it is easy for the software do figure out if just one or more than one predicate is affected.
```
Invalid {{PLURAL:$1|predicate|predicates}}:
$1. Your changes were not saved.
```

**Comment by malberts** [comment]
We can do that. I just need to pass in the count as a separate variable. Unfortunately the plural syntax works with a number and not a PHP array, so the actual list value passed in to the message function is a simple string.
